CREATE TYPE "public"."vocab_level" AS ENUM('Pre-A1', 'A1', 'A2', 'A2+', 'B1', 'B1+', 'B2', 'B2+');--> statement-breakpoint
CREATE TABLE "attempts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attempts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"part_id" integer NOT NULL,
	"typed_text" text NOT NULL,
	"accuracy" real NOT NULL,
	"wpm" real NOT NULL,
	"xp" real NOT NULL,
	"client_attempt_id" uuid NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "attempts_user_part_client_unique" UNIQUE("user_id","part_id","client_attempt_id")
);
--> statement-breakpoint
CREATE TABLE "books" (
	"id" integer PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"title_en" text NOT NULL,
	"title_vi" text,
	"cefr_label" text NOT NULL,
	"exam_target" text,
	"desc_en" text,
	"desc_vi" text,
	"color" text NOT NULL,
	"sort_order" integer NOT NULL,
	CONSTRAINT "books_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "daily_activity" (
	"user_id" text NOT NULL,
	"date" date NOT NULL,
	"parts_done" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "daily_activity_user_id_date_pk" PRIMARY KEY("user_id","date")
);
--> statement-breakpoint
CREATE TABLE "lesson_parts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lesson_parts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"lesson_id" integer NOT NULL,
	"sort_order" integer NOT NULL,
	"text" text NOT NULL,
	"audio_path" text,
	"duration_ms" integer,
	CONSTRAINT "lesson_parts_lesson_id_sort_order_unique" UNIQUE("lesson_id","sort_order")
);
--> statement-breakpoint
CREATE TABLE "lessons" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "lessons_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"unit_id" integer NOT NULL,
	"number" integer NOT NULL,
	"title_en" text NOT NULL,
	"title_vi" text,
	"kind" text DEFAULT 'dictation' NOT NULL,
	"vocab_level" "vocab_level" NOT NULL,
	"sort_order" integer NOT NULL,
	"published" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "lessons_unit_id_number_unique" UNIQUE("unit_id","number")
);
--> statement-breakpoint
CREATE TABLE "units" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "units_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"book_id" integer NOT NULL,
	"number" integer NOT NULL,
	"title_en" text NOT NULL,
	"title_vi" text,
	"desc_en" text,
	"desc_vi" text,
	"sort_order" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "units_book_id_number_unique" UNIQUE("book_id","number")
);
--> statement-breakpoint
CREATE TABLE "user_lesson_progress" (
	"user_id" text NOT NULL,
	"lesson_id" integer NOT NULL,
	"done_parts" integer DEFAULT 0 NOT NULL,
	"best_accuracy" real,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "user_lesson_progress_user_id_lesson_id_pk" PRIMARY KEY("user_id","lesson_id")
);
--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "xp" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "streak_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "last_active_date" date;--> statement-breakpoint
ALTER TABLE "attempts" ADD CONSTRAINT "attempts_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "attempts" ADD CONSTRAINT "attempts_part_id_lesson_parts_id_fk" FOREIGN KEY ("part_id") REFERENCES "public"."lesson_parts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "daily_activity" ADD CONSTRAINT "daily_activity_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lesson_parts" ADD CONSTRAINT "lesson_parts_lesson_id_lessons_id_fk" FOREIGN KEY ("lesson_id") REFERENCES "public"."lessons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "lessons" ADD CONSTRAINT "lessons_unit_id_units_id_fk" FOREIGN KEY ("unit_id") REFERENCES "public"."units"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "units" ADD CONSTRAINT "units_book_id_books_id_fk" FOREIGN KEY ("book_id") REFERENCES "public"."books"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_lesson_progress" ADD CONSTRAINT "user_lesson_progress_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "user_lesson_progress" ADD CONSTRAINT "user_lesson_progress_lesson_id_lessons_id_fk" FOREIGN KEY ("lesson_id") REFERENCES "public"."lessons"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "attempts_user_id_idx" ON "attempts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "attempts_part_id_idx" ON "attempts" USING btree ("part_id");--> statement-breakpoint
CREATE INDEX "lesson_parts_lesson_id_idx" ON "lesson_parts" USING btree ("lesson_id");--> statement-breakpoint
CREATE INDEX "lessons_unit_id_idx" ON "lessons" USING btree ("unit_id");--> statement-breakpoint
CREATE INDEX "units_book_id_idx" ON "units" USING btree ("book_id");--> statement-breakpoint
CREATE INDEX "user_lesson_progress_lesson_id_idx" ON "user_lesson_progress" USING btree ("lesson_id");--> statement-breakpoint
CREATE VIEW "public"."leaderboard" AS (
  SELECT 'weekly'::text AS scope, p.display_name, p.avatar_url,
         SUM(a.xp)::int AS xp
  FROM profiles p
  JOIN attempts a ON a.user_id = p.id
    AND (a.created_at AT TIME ZONE 'Asia/Ho_Chi_Minh')
      >= date_trunc('week', now() AT TIME ZONE 'Asia/Ho_Chi_Minh')
  GROUP BY p.id, p.display_name, p.avatar_url
  UNION ALL
  SELECT 'all_time'::text AS scope, p.display_name, p.avatar_url, p.xp
  FROM profiles p
  WHERE p.xp > 0
);