CREATE TABLE "crawl_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "crawl_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"word" text,
	"source" text DEFAULT 'oxford-ld' NOT NULL,
	"raw" jsonb,
	"ipa_uk" text,
	"ipa_us" text,
	"audio_uk_url" text,
	"audio_us_url" text,
	"audio_uk_blob" text,
	"audio_us_blob" text,
	"pos" text,
	"cefr" text,
	"ox3000" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"attempts" integer DEFAULT 0 NOT NULL,
	"last_error" text,
	"fetched_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "crawl_entries_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
ALTER TABLE "words" ADD COLUMN "cefr" text;--> statement-breakpoint
ALTER TABLE "words" ADD COLUMN "source" text;--> statement-breakpoint
CREATE INDEX "crawl_entries_status_idx" ON "crawl_entries" USING btree ("status");--> statement-breakpoint
CREATE INDEX "crawl_entries_word_idx" ON "crawl_entries" USING btree ("word");