CREATE TABLE "vocab_activity" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "vocab_activity_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"word_id" integer NOT NULL,
	"kind" text NOT NULL,
	"correct" boolean NOT NULL,
	"xp" integer NOT NULL,
	"session_key" text NOT NULL,
	"step_index" integer NOT NULL,
	"attempt_no" integer NOT NULL,
	"idempotency_key" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "vocab_activity_idempotency_key_unique" UNIQUE("idempotency_key"),
	CONSTRAINT "vocab_activity_kind_check" CHECK ("vocab_activity"."kind" in ('learn-complete', 'session-step'))
);
--> statement-breakpoint
ALTER TABLE "daily_activity" ADD COLUMN "vocab_steps" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "profiles" ADD COLUMN "daily_goal_words" integer DEFAULT 5 NOT NULL;--> statement-breakpoint
ALTER TABLE "user_word_progress" ADD COLUMN "lapses" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "vocab_activity" ADD CONSTRAINT "vocab_activity_user_id_profiles_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vocab_activity" ADD CONSTRAINT "vocab_activity_word_id_words_id_fk" FOREIGN KEY ("word_id") REFERENCES "public"."words"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "vocab_activity_user_id_created_at_idx" ON "vocab_activity" USING btree ("user_id","created_at");--> statement-breakpoint
CREATE INDEX "vocab_activity_user_id_word_id_idx" ON "vocab_activity" USING btree ("user_id","word_id");